[package]
name = "api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.3", features = ["json"] }
dashmap = "5.4.0"
log = "0.4.19"
serde = { version = "1.0.164", features = ["derive"] }

[dependencies.atletiek_nu_api]
path = "../atletiek-nu-api"